# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogWindow(object):
    def setupUi(self, DialogWindow):
        DialogWindow.setObjectName("DialogWindow")
        DialogWindow.resize(800, 488)
        self.centralwidget = QtWidgets.QWidget(DialogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 20, 701, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.input_float = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.input_float.setObjectName("input_float")
        self.gridLayout.addWidget(self.input_float, 0, 1, 1, 1)
        self.file_files = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.file_files.setObjectName("file_files")
        self.gridLayout.addWidget(self.file_files, 2, 2, 1, 1)
        self.input_option = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.input_option.setObjectName("input_option")
        self.gridLayout.addWidget(self.input_option, 0, 4, 1, 1)
        self.file_file = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.file_file.setObjectName("file_file")
        self.gridLayout.addWidget(self.file_file, 2, 1, 1, 1)
        self.file_save = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.file_save.setObjectName("file_save")
        self.gridLayout.addWidget(self.file_save, 2, 3, 1, 1)
        self.file_other = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.file_other.setObjectName("file_other")
        self.gridLayout.addWidget(self.file_other, 2, 4, 1, 1)
        self.input_int = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.input_int.setObjectName("input_int")
        self.gridLayout.addWidget(self.input_int, 0, 0, 1, 1)
        self.msg_qa = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.msg_qa.setObjectName("msg_qa")
        self.gridLayout.addWidget(self.msg_qa, 1, 1, 1, 1)
        self.input_txt = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.input_txt.setObjectName("input_txt")
        self.gridLayout.addWidget(self.input_txt, 0, 2, 1, 1)
        self.msg_info = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.msg_info.setObjectName("msg_info")
        self.gridLayout.addWidget(self.msg_info, 1, 0, 1, 1)
        self.msg_dangerous = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.msg_dangerous.setObjectName("msg_dangerous")
        self.gridLayout.addWidget(self.msg_dangerous, 1, 3, 1, 1)
        self.msg_about = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.msg_about.setObjectName("msg_about")
        self.gridLayout.addWidget(self.msg_about, 1, 4, 1, 1)
        self.input_article = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.input_article.setObjectName("input_article")
        self.gridLayout.addWidget(self.input_article, 0, 3, 1, 1)
        self.file_folder = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.file_folder.setObjectName("file_folder")
        self.gridLayout.addWidget(self.file_folder, 2, 0, 1, 1)
        self.msg_warning = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.msg_warning.setObjectName("msg_warning")
        self.gridLayout.addWidget(self.msg_warning, 1, 2, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 360, 701, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.color = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.color.setObjectName("color")
        self.horizontalLayout.addWidget(self.color)
        self.font = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.font.setObjectName("font")
        self.horizontalLayout.addWidget(self.font)
        self.customize = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.customize.setObjectName("customize")
        self.horizontalLayout.addWidget(self.customize)
        DialogWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DialogWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        DialogWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DialogWindow)
        self.statusbar.setObjectName("statusbar")
        DialogWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DialogWindow)
        QtCore.QMetaObject.connectSlotsByName(DialogWindow)

    def retranslateUi(self, DialogWindow):
        _translate = QtCore.QCoreApplication.translate
        DialogWindow.setWindowTitle(_translate("DialogWindow", "DialogTestApp"))
        self.input_float.setText(_translate("DialogWindow", "float"))
        self.file_files.setText(_translate("DialogWindow", "files"))
        self.input_option.setText(_translate("DialogWindow", "option"))
        self.file_file.setText(_translate("DialogWindow", "file"))
        self.file_save.setText(_translate("DialogWindow", "save"))
        self.file_other.setText(_translate("DialogWindow", "other"))
        self.input_int.setText(_translate("DialogWindow", "int"))
        self.msg_qa.setText(_translate("DialogWindow", "Q&A"))
        self.input_txt.setText(_translate("DialogWindow", "text"))
        self.msg_info.setText(_translate("DialogWindow", "information"))
        self.msg_dangerous.setText(_translate("DialogWindow", "dangerous"))
        self.msg_about.setText(_translate("DialogWindow", "about"))
        self.input_article.setText(_translate("DialogWindow", "article"))
        self.file_folder.setText(_translate("DialogWindow", "folder"))
        self.msg_warning.setText(_translate("DialogWindow", "warning"))
        self.color.setText(_translate("DialogWindow", "color"))
        self.font.setText(_translate("DialogWindow", "font"))
        self.customize.setText(_translate("DialogWindow", "customize"))

